name: safeher
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI packages
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1

  # Firebase packages
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  
  # Supabase packages
  supabase_flutter: ^2.5.6
  
  # Location and SMS packages
  geolocator: ^12.0.0
  url_launcher: ^6.3.2
  geocoding: ^3.0.0
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true

# Launcher icon configuration
flutter_launcher_icons:
  image_path: assets/icon.png
  android: true
  ios: true
  web:
    generate: true
    background_color: "#ffffff"
    theme_color: "#1EA7FD"
  macos:
    generate: true
  windows:
    generate: true

# Native splash screen configuration (no logo, plain color)
flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#FFFFFF"   # Background color while app initializes
  android_12:
    color: "#FFFFFF"
  # No 'image' specified on purpose to avoid showing any logo
  fullscreen: true
