// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwOmjFjnylzfFLEP8lD-I_L_Ds0EMPio8',
    appId: '1:948203661952:web:3938b65377c685f91bd465',
    messagingSenderId: '948203661952',
    projectId: 'safeher-g575',
    authDomain: 'safeher-g575.firebaseapp.com',
    storageBucket: 'safeher-g575.firebasestorage.app',
    measurementId: 'G-CXSEQF1T2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWdDqOrDGLGclXG707_pQr7cyTyzse9ak',
    appId: '1:948203661952:android:fdbb222e083fd5d11bd465',
    messagingSenderId: '948203661952',
    projectId: 'safeher-g575',
    storageBucket: 'safeher-g575.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn-sED4GviBKvGObfZo_po0c-d2QIQBOk',
    appId: '1:948203661952:ios:2462d7d5515095021bd465',
    messagingSenderId: '948203661952',
    projectId: 'safeher-g575',
    storageBucket: 'safeher-g575.firebasestorage.app',
    iosBundleId: 'com.example.safeher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn-sED4GviBKvGObfZo_po0c-d2QIQBOk',
    appId: '1:948203661952:ios:2462d7d5515095021bd465',
    messagingSenderId: '948203661952',
    projectId: 'safeher-g575',
    storageBucket: 'safeher-g575.firebasestorage.app',
    iosBundleId: 'com.example.safeher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwOmjFjnylzfFLEP8lD-I_L_Ds0EMPio8',
    appId: '1:948203661952:web:5c82a10fbe2472d21bd465',
    messagingSenderId: '948203661952',
    projectId: 'safeher-g575',
    authDomain: 'safeher-g575.firebaseapp.com',
    storageBucket: 'safeher-g575.firebasestorage.app',
    measurementId: 'G-E1K6C6TZVF',
  );
}
