// lib/main.dart
import 'dart:async'; // for runZonedGuarded

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart'; // keep for later (contacts storage)
import 'firebase_options.dart';

import 'safe_her_welcome_screen.dart';
import 'login_screen.dart';
import 'otp_verification_screen.dart'; // if you navigate to it elsewhere

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ Important on web: initialize with platform options generated by flutterfire
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Log uncaught framework errors (prevents silent white screens)
  FlutterError.onError = (FlutterErrorDetails details) {
    FlutterError.dumpErrorToConsole(details);
  };

  try {
    runApp(const SafeHerApp());
  } catch (error, stack) {
    print('App startup error: $error\n$stack');
  }
}

class SafeHerApp extends StatelessWidget {
  const SafeHerApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SafeHer',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: const AuthWrapper(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        // Loading state while Firebase/Auth initializes
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(
            body: Center(child: CircularProgressIndicator()),
          );
        }

        // Show any auth stream error instead of a blank screen
        if (snapshot.hasError) {
          return Scaffold(
            body: Center(
              child: Padding(
                padding: const EdgeInsets.all(24.0),
                child: Text(
                  'Authentication error:\n${snapshot.error}',
                  textAlign: TextAlign.center,
                ),
              ),
            ),
          );
        }

        // Navigate based on login state
        if (snapshot.hasData) {
          // User logged in → Welcome/Home
          return const SafeHerWelcomeScreen();
        } else {
          // Not logged in → Login screen
          return const LoginScreen();
        }
      },
    );
  }
}

